//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental {
	
	
	public partial class AddReview{
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DropDownList rateDropDown;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatoRate;
		
		protected System.Web.UI.WebControls.TextBox reviewTxtBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorReview;
		
		protected System.Web.UI.WebControls.Button submit;
	}
}
