//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental {
	
	
	public partial class SignIn {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.TextBox uTxtBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorEmail;
		
		protected System.Web.UI.WebControls.TextBox passwordTxtBox;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorPassword;
		
		protected System.Web.UI.WebControls.Button submit;
	}
}
